name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
    MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
    MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        env:
          MONGO_URI: mongodb://localhost:27017/superData 
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Cache NPM Dependencies 
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: "${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}"
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v4   
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code-coverage:
     name: Code Coverage
     container:
       image: node:18
     services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            options:
              --name mongo
     env:
        MONGO_URI: mongodb://mongo:27017/superData 
        MONGO_USERNAME: non-prod-user
        MONGO_PASSWORD: non-prod-password

     runs-on: ubuntu-latest
     continue-on-error: true
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v4

    #  - name: Setup NodeJS Version
    #    uses: actions/setup-node@v4  
    #    with:
    #     node-version: 18

     - name: Install Dependencies
       run: npm install

     - name: Check Code Coverage
       run: npm run coverage
       continue-on-error: true

     - name: Archive Test Result
       uses: actions/upload-artifact@v4  
       with:
        name: Code-Coverage-Result
        path: coverage
        retention-days: 5  
        
    docker:
      name: Containerization
      needs: [code-coverage]
      permissions:
        packages: write

      runs-on: ubuntu-latest 
      steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Github Container Registry Login
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} 
          password: ${{ secrets.TOKENS_GITHUB }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      - name: Docker image Test 
        run: |
          docker images
          docker run --name solar-system-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              -e MONGO_USERNAME=$MONGO_USERNAME \
              -e MONGO_PASSWORD=$MONGO_PASSWORD \
              ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          
          # Get the container's internal IP
          export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo "Container IP: $IP"

          # Test the image URL
          echo "Testing image URL using Wget"
          wget -q -O - 127.0.0.1:3000/live | grep live 

      - name: Push Image to DockerHub & GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
              ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}

    dev-deploy: 
      needs: docker
      runs-on: ubuntu-latest  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4  

        - name: Install Kubectl CLI
          uses: azure/setup-kubectl@v4
          with:
            version: 'v1.30.0'
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2  # Update to your EKS region
          
        - name: Update Kubeconfig for EKS
          run: aws eks update-kubeconfig --region us-east-2 --name staging-demo
      
        # - uses: azure/k8s-set-context@v4
        #   with:
        #     method: kubeconfig
        #     kubeconfig: ${{ secrets.KUBECONFIG }}
        
        - name: Fetch Kubernetes Cluster Details
          run: |
             kubectl version --output=yaml  # Fixed version command
             echo --------------------------
             kubectl get nodes

        - name: Replace Token in Manifast files
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: 'kubernetes/development/*.yaml'
          env:
            NAMESPACE: "${{ secrets.NAMESPACE }}"
            REPLICAS: "${{ secrets.REPLICAS }}"
            IMAGE: "${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}"

        - name: Check Final Kubernetes Manifests
          run: |
             cat kubernetes/development/*.yaml

        - name: Apply Kubernetes Manifests
          run: |
             kubectl apply -f kubernetes/development/
             kubectl get ingress solar-system -n development -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'



       
 






